apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/elasticsearch-eck-operator-certified.openshift-operators: ""
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elasticsearch-eck-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elasticsearch-eck-operator-certified.v2.8.0
